name: CI-OSX-Test

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: |
          brew update
          brew install llvm@20 lld@20 bash socat wget cmake meson

      - name: Build SDK
        run: |
          make DESTDIR=${{ runner.tool_cache }}/ps5-payload-sdk install
          PS5_PAYLOAD_SDK=${{ runner.tool_cache }}/ps5-payload-sdk ./libcxx.sh
          cd ${{ runner.tool_cache }}
          zip -r $GITHUB_WORKSPACE/ps5-payload-sdk.zip ps5-payload-sdk
          cd -

      - name: Build Tests
        run: |
          export PS5_PAYLOAD_SDK=${{ runner.tool_cache }}/ps5-payload-sdk
          make -C samples/test_privileges

